<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>eling</AssemblyName>
    <StartBeforeBuildEnabled>true</StartBeforeBuildEnabled>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Eling.Mcp\Eling.Mcp.csproj" />
  </ItemGroup>

</Project>
